### ISSUE TITLE
No files in src/libinterpol/ext/spline

### ISSUE THREAD

**Issue by icameling** [adrelino/interpolation-methods#1]
Hi, thanks a lot for the nice work.
When I compile the code, there's a error
```
can't find spline.h
```
I download the spline library from [here](https://github.com/ttk592/spline/) and compile again,
there's another error
```
/home/ha/ws_github/interpolation-methods/src/libinterpol/include/interpol/euclidean/bezier.hpp:77: error: ‘class {anonymous}::tk::spline’ has no member named ‘control_polygon’
                     p(j) = splines[j].control_polygon(i, k);
                          ^
```
The class `tk::spline` has no  member  `control_polygon`.
Could you update your code? Thanks!

**Comment by adrelino** [comment]
Sorry, just saw this issue now.  You need to init the submodules like so: `git submodule update --init`. Maybe I should add that to the readme. I forked the tk::spline repo into my account and added the method to get the control polygon that's why it won't work with the original one. I also use Sophus for SE3 as submodule. See here: https://github.com/adrelino/interpolation-methods/blob/master/.gitmodules
